/aruco_detect:
  ros__parameters:
    camera_alpha: 0.0
    front_camera_image: pupil_glasses/front_camera/image_color
    front_camera_params: pupil_glasses/front_camera/camera_info
    publish_drawn_marker: True
    marker_length: 0.035
    aruco_dict: 1 # DICT_4X4_100
# Properties at https://docs.opencv.org/3.4/d9/d6a/group__aruco.html
